name: Run Script and Notify on Changes

on:
  workflow_dispatch:  # Allow manual triggering
  schedule:
    - cron: "*/10 * * * *"  # Run every 10 minutes

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: pip install selenium

      - name: Run the script
        run: python fetch_videos.py  # Execute the Python script

      - name: Commit and push results
        run: |
          git config --global user.name "GitHub Actions Bot"
          git config --global user.email "actions@github.com"
          git add video_data.json
          git diff-index --quiet HEAD || git commit -m "Update video data"
          git push

      - name: Check for changes
        id: check_changes
        run: |
          if git diff --name-only | grep -q "video_data.json"; then
            echo "changes_detected=true" >> $GITHUB_ENV
          else
            echo "changes_detected=false" >> $GITHUB_ENV

      - name: Send email notification
        if: env.changes_detected == 'true'
        run: |
          echo "New video data has been added! Check out the latest changes in the repository." | mail -s "New Video Alert" your_email@example.com
